/*
  Warnings:

  - You are about to alter the column `id` on the `Character` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_Character" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "name" STRING NOT NULL,
    "animeTitle" STRING NOT NULL,
    "species" STRING NOT NULL,
    "age" INT4 NOT NULL,
    "gender" STRING NOT NULL,
    "appearance" STRING[],
    "role" STRING NOT NULL,
    "voiceActor" STRING NOT NULL,

    CONSTRAINT "Character_pkey" PRIMARY KEY ("id")
);
DROP INDEX "Character_id_key";
INSERT INTO "_prisma_new_Character" ("age","animeTitle","appearance","createdAt","gender","id","name","role","species","updatedAt","voiceActor") SELECT "age","animeTitle","appearance","createdAt","gender","id","name","role","species","updatedAt","voiceActor" FROM "Character";
DROP TABLE "Character" CASCADE;
ALTER TABLE "_prisma_new_Character" RENAME TO "Character";
CREATE UNIQUE INDEX "Character_id_key" ON "Character"("id");
